
//light particles only interact with obstacles and units
//light particles are generated by light sources, and move at a uniform speed
class LightParticle{
  float x, y, dir, radius, speed;
  boolean alive;
  LightParticle(float xin, float yin, float dirIn){
    x = xin;
    y = yin;
    dir = dirIn;//direction
    radius = 2;
    speed = 2;//this is the speed of light!
    alive = false;
  }
  
  void update(){
    if(x > width+radius || x < 0-radius || 
       y > height+radius || y < 0-radius){//exits bounds
        alive = false;//DIE!
    }//end if
    
    
  }//end update()
  
  void draw(){
    
  
  }

  void collide(){}//checks for collisions

  //move, using speed and direction
  void move(){
  
  }

}

//manages all light particles
class LightSystem{
  LightSystem(){}
}


